source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StoryboardPod_Example', :exclusive => true do
  pod 'StoryboardPod', :path => '../'
end

target 'StoryboardPod_Tests', :exclusive => true do
  pod 'StoryboardPod', :path => '../'

  
end
